### ISSUE TITLE
PulseEffects Compatibility

### ISSUE THREAD

**Issue by sysv0id** [Audio4Linux/Viper4Linux-GUI#6]
V4L and PE work together after some workaround. Restarting V4L after opening PE and pointing PE output to "viper" then to whatever device you are listening to. I have no problem with this because it's working. 

But the issue comes when the media stops. When the volume reaches down to zero, V4L would stop working but not PE. Any other workaround for this?

**Comment by noahbliss** [comment]
@jdotdarko I read over your comment and the issue here is deeper than it seems. Viper4Linux is "greedy" with how it handles input streams and core functionality would break if we changed this behavior. To solve this issue I created a new branch of Viper4Linux [sinkhole-daisychain](https://github.com/Audio4Linux/Viper4Linux/tree/sinkhole-daisychain) which routes audio to a new sink: viper-out. I tested this with PulseEffects on Arch with GNOME and had expected behavior. 

Please note, you should only attach to viper-out. The viper sink itself is essentially "viper in" and will likely _not_ give you processed output. Use PulseEffects to do your final routing with "viper-out" as the input, and your actual speakers as its output. You may need to cycle your output device in the PulseEffects GUI for it to start working. 

Let me know how it goes!

**Comment by noahbliss** [comment]
Another note, in PulseEffects, select **only** gst-launch-1.0 as the processing application. If you select the actual origin app, then it will steal it from Viper and bypass our processing.

**Comment by sysv0id** [comment]
Confirmed working even after the audio from a media stops! Tested on Arch with KDE. Just have to cycle V4L and PE which is no big deal to me as long as they're both working together throughout my desktop sessions. Thank you!

**Comment by noahbliss** [comment]
Great to hear, thanks for the report!
